spring.application.name=product-service

# MongoDB Configuration
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=mydatabase
spring.mongodb.username=admin
spring.mongodb.password=admin123
spring.mongodb.authentication-database=admin


# MongoDB Options
spring.data.mongodb.auto-index-creation=true

# Eureka Client - Register with Discovery Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.mongodb=DEBUG